image: docker/compose:1.23.2

options:
    docker: true

pipelines:
    default:
        -   step:
                caches:
                    - docker
                script:
                    - apk add --no-cache bash make
                    - docker-compose -v

                    - make init
                    - make lint
                    - make test

                    - make docker-down-clear || true
