version: '3.7'
services:
    site:
        image: ${REGISTRY}/site:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        volumes:
            - site-assets:/app/public/assets:ro
            - site-upload:/app/public/upload:ro
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.services.site.loadbalancer.server.port=80
                - traefik.http.routers.site.rule=Host(`elisdn.ru`) || Host(`www.elisdn.ru`)
                - traefik.http.middlewares.site-redirect.redirectregex.regex=^(https?://)www.elisdn.ru/(.*)$$
                - traefik.http.middlewares.site-redirect.redirectregex.replacement=$${1}elisdn.ru$${2}
                - traefik.http.middlewares.site-redirect.redirectregex.permanent=true
                - traefik.http.routers.site.middlewares=site-redirect
                - traefik.http.routers.site.entrypoints=https
                - traefik.http.routers.site.tls=true
                - traefik.http.routers.site.tls.certresolver=letsencrypt
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    site-php-fpm:
        image: ${REGISTRY}/site-php-fpm:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: site-redis
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            DEWORKER_API_URL: https://api.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - site-assets:/app/public/assets
            - site-upload:/app/public/upload
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    site-migration:
        image: ${REGISTRY}/site-php-cli:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: site-redis
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            DEWORKER_API_URL: https://api.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - site-assets:/app/public/assets
            - site-upload:/app/public/upload
        command: sh -c 'wait-for-it ${DB_HOST}:3306 -t 60 && php bin/app.php migrate --interactive=0'
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s
            placement:
                constraints: [node.role == manager]
    site-redis:
        image: redis:6.2-alpine
        volumes:
            - site-redis:/data
        command:
            - 'redis-server'
            - "--requirepass ${REDIS_PASSWORD}"
        deploy:
            placement:
                constraints: [node.labels.db == db]
            endpoint_mode: dnsrr

volumes:
    site-assets:
    site-upload:
    site-redis:

networks:
    traefik-public:
        external: true
