version: '3.9'
services:
    site:
        image: ${REGISTRY}/site:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        volumes:
            - site-assets:/app/public/assets:ro
            - site-upload:/app/public/upload:ro
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.services.site.loadbalancer.server.port=80
                - traefik.http.routers.site.rule=Host(`elisdn.ru`) || Host(`www.elisdn.ru`)
                - traefik.http.middlewares.site-redirect.redirectregex.regex=^(https?://)www.elisdn.ru/(.*)$$
                - traefik.http.middlewares.site-redirect.redirectregex.replacement=$${1}elisdn.ru$${2}
                - traefik.http.middlewares.site-redirect.redirectregex.permanent=true
                - traefik.http.routers.site.middlewares=site-redirect
                - traefik.http.routers.site.entrypoints=https
                - traefik.http.routers.site.tls=true
                - traefik.http.routers.site.tls.certresolver=letsencrypt
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    site-php-fpm:
        image: ${REGISTRY}/site-php-fpm:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: site-mysql
            DB_NAME: app
            DB_USERNAME: app
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: site-redis
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            DEWORKER_API_URL: https://api.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - site-assets:/app/public/assets
            - site-upload:/app/public/upload
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]
    site-migration:
        image: ${REGISTRY}/site-php-cli:${IMAGE_TAG}
        environment:
            APP_DEBUG: 0
            APP_ENV: prod
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: site-mysql
            DB_NAME: app
            DB_USERNAME: app
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: site-redis
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            DEWORKER_API_URL: https://api.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - site-assets:/app/public/assets
            - site-upload:/app/public/upload
        command: sh -c 'wait-for-it site-mysql:3306 -t 60 && php bin/app.php migrate --interactive=0'
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s
            placement:
                constraints: [node.role == manager]
    site-mysql:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: app
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: app
        volumes:
            - site-mysql:/var/lib/mysql
        deploy:
            placement:
                constraints: [node.labels.db == db]
            endpoint_mode: dnsrr
    site-mysql-backup:
        image: ${REGISTRY}/site-mysql-backup:${IMAGE_TAG}
        environment:
            MYSQL_HOST: site-mysql
            MYSQL_USER: app
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DB: app
            AWS_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${BACKUP_AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${BACKUP_AWS_DEFAULT_REGION}
            S3_ENDPOINT: ${BACKUP_S3_ENDPOINT}
            S3_BUCKET: ${BACKUP_S3_BUCKET}
        command: sh -c 'wait-for-it site-mysql:3306 -t 60 && backup'
        deploy:
            labels:
                - swarm.cronjob.enable=true
                - swarm.cronjob.schedule=0 * * * *
                - swarm.cronjob.skip-running=true
            replicas: 0
            restart_policy:
                condition: none
    site-upload-backup:
        image: ${REGISTRY}/site-files-backup:${IMAGE_TAG}
        environment:
            TARGET: /upload
            BACKUP_NAME: upload
            AWS_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${BACKUP_AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${BACKUP_AWS_DEFAULT_REGION}
            S3_ENDPOINT: ${BACKUP_S3_ENDPOINT}
            S3_BUCKET: ${BACKUP_S3_BUCKET}
        volumes:
            - site-upload:/upload:ro
        deploy:
            labels:
                - swarm.cronjob.enable=true
                - swarm.cronjob.schedule=10 * * * *
                - swarm.cronjob.skip-running=true
            replicas: 0
            restart_policy:
                condition: none
    site-redis:
        image: redis:6.2-alpine
        volumes:
            - site-redis:/data
        command:
            - 'redis-server'
            - "--requirepass ${REDIS_PASSWORD}"
        deploy:
            placement:
                constraints: [node.labels.db == db]
            endpoint_mode: dnsrr

volumes:
    site-mysql:
    site-assets:
    site-upload:
    site-redis:

networks:
    traefik-public:
        external: true
