apiVersion: v1
kind: Secret
metadata:
  name: site-mailer
  namespace: elisdn
type: Opaque
stringData:
  host: "${MAILER_HOST}"
  port: "${MAILER_PORT}"
  username: "${MAILER_USERNAME}"
  password: "${MAILER_PASSWORD}"
  fromEmail: "${MAILER_FROM_EMAIL}"
