apiVersion: v1
kind: Secret
metadata:
  name: site-db
  namespace: elisdn
type: Opaque
stringData:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_DATABASE}"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
