version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01

        steps:
            - checkout

            -   restore_cache:
                    keys:
                        - vendor-{{ checksum "composer.lock" }}

            -   restore_cache:
                    keys:
                        - node_modules-{{ checksum "yarn.lock" }}

            -   run:
                    name: Init
                    command: make init

            -   save_cache:
                    key: vendor-{{ checksum "composer.lock" }}
                    paths:
                        - vendor

            -   save_cache:
                    key: node_modules-{{ checksum "yarn.lock" }}
                    paths:
                        - node_modules

            -   run:
                    name: Lint
                    command: make lint

            -   run:
                    name: Test
                    command: make test

            -   store_artifacts:
                    path: ./tests/_output
                    prefix: tests
                    when: always

            -   run:
                    name: Deploy
                    command: HOST=$DEPLOY_HOST PORT=$DEPLOY_PORT DIR=$DEPLOY_PATH REVISION=$CIRCLE_SHA1 make deploy

workflows:
    version: 2
    workflow:
        jobs:
            -   build:
                    filters:
                        branches:
                            only: master
