version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01

        steps:
            - checkout

            -   restore_cache:
                    keys:
                        - vendor-{{ .Branch }}-{{ checksum "composer.lock" }}
                        - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
                        - mysql-{{ .Branch }}

            -   run:
                    name: Init
                    command: make refresh

            -   run:
                    name: Lint
                    command: make lint

            -   run:
                    name: Test
                    command: make test

            -   run:
                    name: Down
                    command: make docker-down-clear

            -   save_cache:
                    key: vendor-{{ .Branch }}-{{ checksum "composer.lock" }}
                    paths:
                        - vendor

            -   save_cache:
                    key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    paths:
                        - node_modules

            -   save_cache:
                    key: mysql-{{ .Branch }}
                    paths:
                        - volumes/mysql

            -   run:
                    name: Deploy
                    command: HOST=$DEPLOY_HOST PORT=$DEPLOY_PORT DIR=$DEPLOY_PATH REVISION=$CIRCLE_SHA1 make deploy

workflows:
    version: 2
    workflow:
        jobs:
            -   build:
                    filters:
                        branches:
                            only: master
