version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01

        steps:
            - checkout

            - run:
                  name: Init
                  command: make init

            - run:
                  name: Lint
                  command: make lint

            - run:
                  name: Test
                  command: make test

workflows:
    version: 2
    workflow:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
