
<?php $this->widget('DGridView', array(
    'id'=>'posts-grid',
    'dataProvider'=>$model->search(50),
    'filter'=>$model,
    'columns'=>array(
        array(
            'class'=>'DLinkColumn',
            'name'=>'id',
            'value' => '$data->fullId',
            'link' => 'Yii::app()->controller->createUrl("view", array("id"=>$data->id))',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'class'=>'DLinkColumn',
            'name'=>'date',
            'link' => 'Yii::app()->controller->createUrl("view", array("id"=>$data->id))',
            'htmlOptions'=>array('style'=>'width:130px;text-align:center'),
        ),
        array(
            'name' => 'fio',
            'header'=>'ФИО',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'name' => 'email',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'name' => 'phone',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'class'=>'DToggleColumn',
            'name'=>'quickly',
            'header'=>'С',
            'filter'=>array(1=>'Срочный', 0=>'Не срочный'),
            'titles'=>array(1=>'Срочный', 0=>'Не срочный'),
            'htmlOptions'=>array('style'=>'width:30px;text-align:center'),
            'onImageUrl'=>Yii::app()->request->baseUrl . '/core/images/admin/important.png',
            'offImageUrl'=>Yii::app()->request->baseUrl . '/core/images/spacer.gif',
            'linkUrl'=>false,
        ),
        array(
            'class'=>'DToggleColumn',
            'name'=>'apply',
            'header'=>'П',
            'filter'=>array(1=>'Принят', 0=>'Не принят'),
            'titles'=>array(1=>'Принят', 0=>'Не принят'),
            'confirmation'=>'Изменить статус?',
            'htmlOptions'=>array('style'=>'width:30px;text-align:center'),
            'offImageUrl'=>Yii::app()->request->baseUrl . '/core/images/spacer.gif',
        ),
        array(
            'class'=>'DToggleColumn',
            'name'=>'payed',
            'header'=>'$',
            'filter'=>array(1=>'Оплачен', 0=>'Не оплачен'),
            'titles'=>array(1=>'Оплачен', 0=>'Не оплачен'),
            'confirmation'=>'Изменить статус?',
            'htmlOptions'=>array('style'=>'width:30px;text-align:center'),
            'offImageUrl'=>Yii::app()->request->baseUrl . '/core/images/spacer.gif',
        ),
        array(
            'class'=>'DToggleColumn',
            'name'=>'complete',
            'header'=>'О',
            'filter'=>array(1=>'Отправлен', 0=>'Не отправлен'),
            'titles'=>array(1=>'Отправлен', 0=>'Не отправлен'),
            'htmlOptions'=>array('style'=>'width:30px;text-align:center'),
            'offImageUrl'=>Yii::app()->request->baseUrl . '/core/images/spacer.gif',
        ),
        array(
            'class'=>'DButtonColumn',
            'htmlOptions'=>array('style'=>'width:20px;text-align:center'),
            'template'=>'{view}',
        ),
        array(
            'class'=>'DButtonColumn',
            'htmlOptions'=>array('style'=>'width:20px;text-align:center'),
            'template'=>'{delete}',
        ),
    ),
)); ?>