name: Pipeline

on:
    push:
        branches:
            - master
    workflow_dispatch:
        branches:
            - master

env:
    REGISTRY_HOST: ghcr.io
    IMAGE_TAG: master-${{ github.run_number }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   uses: actions/checkout@v6

            -   name: Cache vendors
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Cache node modules
                uses: actions/cache@v5
                with:
                    path: node_modules
                    key: yarn-${{ hashFiles('yarn.lock') }}

            -   name: Set registry env
                run: echo "REGISTRY=${{ env.REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

            -   name: Docker login
                uses: azure/docker-login@v2
                with:
                    login-server: ${{ env.REGISTRY_HOST }}
                    username: ${{ github.actor }}
                    password: ${{ github.token }}

            -   name: Init
                run: make init

            -   name: Push dev cache
                run: make push-dev-cache

            -   name: Valid
                run: make app-composer-validate

            -   name: Lint
                run: make app-lint

            -   name: Lint Assets
                run: make app-assets-lint

            -   name: Analyze
                run: make app-analyze

            -   name: Test
                run: make app-test-unit-integration

            -   name: Backup MySQL
                run: make app-backup-mysql

            -   name: Backup uploads
                run: make app-backup-upload

            -   name: Down
                run: make docker-down-clear

            -   name: Build
                run: make build

            -   name: Push build cache
                run: make push-build-cache

            -   name: Testing Build
                run: make testing-build

            -   name: Testing Push build cache
                run: make testing-push-build-cache

            -   name: Testing Init
                run: make testing-init

            -   name: Testing E2E
                id: testing_e2e
                run: make testing-e2e

            -   name: Archive test output
                uses: actions/upload-artifact@v7
                with:
                    name: test-output
                    path: tests/_output
                if: ${{ failure() && steps.testing_e2e.outcome == 'failure' }}

            -   name: Testing Down
                run: make testing-down-clear

            -   name: Push
                run: make push

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read

        steps:
            -   uses: actions/checkout@v6

            -   name: Install Kubectl
                uses: azure/setup-kubectl@v5
                with:
                    version: 'v1.35.3'

            -   name: Kube Config
                run: |
                    mkdir ~/.kube
                    envsubst < .github/kube-config.yaml > ~/.kube/config
                env:
                    SERVER: ${{ secrets.PRODUCTION_KUBERNETES_SERVER }}
                    TOKEN: ${{ secrets.PRODUCTION_KUBERNETES_TOKEN }}

            -   name: Set registry env
                run: echo "REGISTRY=${{ env.REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

            -   name: Deploy
                run: make deploy
                env:
                    COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
                    DB_HOST: ${{ secrets.DB_HOST }}
                    DB_PORT: ${{ secrets.DB_PORT }}
                    DB_DATABASE: ${{ secrets.DB_DATABASE }}
                    DB_USERNAME: ${{ secrets.DB_USERNAME }}
                    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    REDIS_HOST: ${{ secrets.REDIS_HOST }}
                    REDIS_PORT: ${{ secrets.REDIS_PORT }}
                    REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
                    MAILER_HOST: ${{ secrets.MAILER_HOST }}
                    MAILER_PORT: ${{ secrets.MAILER_PORT }}
                    MAILER_USERNAME: ${{ secrets.MAILER_USERNAME }}
                    MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
                    MAILER_FROM_EMAIL: ${{ secrets.MAILER_FROM_EMAIL }}
                    SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
                    BACKUP_AWS_ACCESS_KEY_ID: ${{ secrets.BACKUP_AWS_ACCESS_KEY_ID }}
                    BACKUP_AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKUP_AWS_SECRET_ACCESS_KEY }}
                    BACKUP_AWS_DEFAULT_REGION: ${{ secrets.BACKUP_AWS_DEFAULT_REGION }}
                    BACKUP_S3_ENDPOINT: ${{ secrets.BACKUP_S3_ENDPOINT }}
                    BACKUP_S3_BUCKET: ${{ secrets.BACKUP_S3_BUCKET }}

    clean:
        runs-on: ubuntu-latest
        needs: deploy

        steps:
            -   uses: quartx-analytics/ghcr-cleaner@v1
                with:
                    owner-type: org
                    token: ${{ secrets.REGISTRY_CLEAR_TOKEN }}
                    repository-owner: ${{ github.repository_owner }}
                    repository-name: ${{ github.repository }}
                    delete-untagged: true
                    filter-tags: master-*
                    keep-at-most: 5
                    skip-tags: latest,cache,cache-builder,dev-cache
