name: Pipeline

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache vendors
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

            -   name: Cache node modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

            -   name: Init
                run: make init

            -   name: Valid
                run: make site-composer-validate

            -   name: Lint
                run: make site-lint

            -   name: Analyze
                run: make site-analyze

            -   name: Test
                run: make site-test

            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: Deploy
                run: REVISION=$GITHUB_SHA make deploy
                env:
                    HOST: ${{ secrets.DEPLOY_HOST }}
                    PORT: ${{ secrets.DEPLOY_PORT }}
                    DIR: ${{ secrets.DEPLOY_PATH }}

