name: Pipeline

on:
    push:
        branches:
            - master

env:
    REGISTRY_HOST: ghcr.io
    REGISTRY: ghcr.io/elisdnru/site
    IMAGE_TAG: master-${{ github.run_number }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache vendors
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Cache node modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: yarn-${{ hashFiles('yarn.lock') }}

            -   name: Docker login
                uses: azure/docker-login@v1
                with:
                    login-server: ${{ env.REGISTRY_HOST }}
                    username: ElisDN
                    password: ${{ github.token }}

            -   name: Init
                run: make init

            -   name: Push dev cache
                run: make push-dev-cache

            -   name: Valid
                run: make site-composer-validate

            -   name: Lint
                run: make site-lint

            -   name: Analyze
                run: make site-analyze

            -   name: Test
                run: make site-test

            -   name: Archive test output
                uses: actions/upload-artifact@v1
                with:
                    name: test-output
                    path: tests/_output
                if: ${{ failure() }}

            -   name: Backup MySQL
                run: make site-backup-mysql

            -   name: Backup uploads
                run: make site-backup-upload

            -   name: Down
                run: make down

            -   name: Build
                run: make build

            -   name: Push build cache images
                run: make push-build-cache

            -   name: Push
                run: make push

            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_KEY }}
                    known_hosts: ${{ secrets.DEPLOY_HOST }}

            -   name: Secrets
                run: |
                    echo "${{ secrets.COOKIE_SECRET }}" > /tmp/cookie_secret
                    echo "${{ secrets.DB_PASSWORD }}" > /tmp/db_password
                    echo "${{ secrets.REDIS_PASSWORD }}" > /tmp/redis_password
                    echo "${{ secrets.MAILER_PASSWORD }}" > /tmp/mailer_password
                    echo "${{ secrets.SENTRY_DSN }}" > /tmp/sentry_dsn
                    echo "${{ secrets.BACKUP_AWS_SECRET_ACCESS_KEY }}" > /tmp/backup_aws_secret_access_key

            -   name: Deploy
                run: make deploy
                env:
                    BUILD_NUMBER: ${{ github.run_number }}
                    HOST: ${{ secrets.DEPLOY_HOST }}
                    PORT: ${{ secrets.DEPLOY_PORT }}
                    COOKIE_SECRET_FILE: /tmp/cookie_secret
                    DB_HOST: ${{ secrets.DB_HOST }}
                    DB_NAME: ${{ secrets.DB_NAME }}
                    DB_USERNAME: ${{ secrets.DB_USERNAME }}
                    DB_PASSWORD_FILE: /tmp/db_password
                    REDIS_PASSWORD_FILE: /tmp/redis_password
                    MAILER_HOST: ${{ secrets.MAILER_HOST }}
                    MAILER_PORT: ${{ secrets.MAILER_PORT }}
                    MAILER_USER: ${{ secrets.MAILER_USER }}
                    MAILER_PASSWORD_FILE: /tmp/mailer_password
                    MAILER_FROM_EMAIL: ${{ secrets.MAILER_FROM_EMAIL }}
                    SENTRY_DSN_FILE: /tmp/sentry_dsn
                    BACKUP_AWS_ACCESS_KEY_ID: ${{ secrets.BACKUP_AWS_ACCESS_KEY_ID }}
                    BACKUP_AWS_SECRET_ACCESS_KEY_FILE: /tmp/backup_aws_secret_access_key
                    BACKUP_AWS_DEFAULT_REGION: ${{ secrets.BACKUP_AWS_DEFAULT_REGION }}
                    BACKUP_S3_ENDPOINT: ${{ secrets.BACKUP_S3_ENDPOINT }}
                    BACKUP_S3_BUCKET: ${{ secrets.BACKUP_S3_BUCKET }}
