name: Pipeline

on:
    push:
        branches:
            - master

env:
    REGISTRY: docker.pkg.github.com/elisdn/elisdn.ru
    REGISTRY_HOST: docker.pkg.github.com

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache vendors
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Cache node modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: yarn-${{ hashFiles('yarn.lock') }}

            -   name: Docker login
                uses: azure/docker-login@v1
                with:
                    login-server: ${{ env.REGISTRY_HOST }}
                    username: ElisDN
                    password: ${{ github.token }}

            -   name: Inject slug variables
                uses: rlespinasse/github-slug-action@v2.x

            -   name: Init
                run: make init
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Push dev cache
                run: make push-dev-cache
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Valid
                run: make site-composer-validate
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Cache phplint
                uses: actions/cache@v2
                with:
                    path: var/.phplint.json
                    key: phplint-${{ hashFiles('var/.phplint.json') }}

            -   name: Cache phpcs
                uses: actions/cache@v2
                with:
                    path: var/.phpcs.json
                    key: phpcs-${{ hashFiles('var/.phpcs.json') }}

            -   name: Lint
                run: make site-lint
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Analyze
                run: make site-analyze
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Test
                run: make site-test
                env:
                    CACHE_TAG: ${{ env.GITHUB_REF_SLUG }}

            -   name: Archive test output
                uses: actions/upload-artifact@v1
                with:
                    name: test-output
                    path: tests/_output
                if: ${{ failure() }}

            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: Deploy
                run: make deploy
                env:
                    HOST: ${{ secrets.DEPLOY_HOST }}
                    PORT: ${{ secrets.DEPLOY_PORT }}
                    DIR: ${{ secrets.DEPLOY_PATH }}
                    REVISION: ${{ github.sha }}
